Repository hmcts/prl-dgs-api, pull requests merged in 2022-08, with the labels that each got.

#140 FPET-34 DGS changes for C1A & C8 Draft
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-140

#165 Add backstage configuration file
  catalog-info.yaml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-165

#155 Release 2.2 features
  README.md
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-155
