Repository hmcts/prl-dgs-api, pull requests merged in 2022-10, with the labels that each got.

#182 FPET-179 Upgraded jackson to 2.14.0-rc1to fix Nightly build
  build.gradle
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-182

#180 Feature/prl 2128 ca citizen resp download
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-180

#184 Welsh template changes
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-184

#185 Welsh translations for FL402 document
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-185
