Repository hmcts/prl-dgs-api, pull requests merged in 2022-11, with the labels that each got.

#188 Welsh translations for C43 & C43A order document
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-188

#189 Welsh translation orders C47A
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-189

#190 Welsh translations for C45A document
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-190

#192 Add the required versionof dependency
  build.gradle
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-192

#195 Chart upgrade for dgs-api
  charts/prl-dgs/Chart.yaml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-195
