Repository hmcts/prl-dgs-api, pull requests merged in 2022-06, with the labels that each got.

#138 FPET-36 fixed CVE errors and updated suppressions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-138

#123 Prl 1316 fl404a dev
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-123

#129 Added chnages for FL404a
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-129

#125 Prl 1357 docs update
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-125
