Repository hmcts/prl-dgs-api, pull requests merged in 2022-04, with the labels that each got.

#90 Merge to master
  build.gradle
  charts/prl-dgs/Chart.yaml
  config/owasp/suppressions.xml
  dependency-check-suppressions.xml
  src/contractTest/java/uk/gov/hmcts/reform/prl/documentgenerator/CdamApiConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/prl/documentgenerator/PdfGenerationServiceConsumerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/DocumentGenerateControllerFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/ResourceLoader.java
  src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/RootControllerFunctionalTest.java
  src/functionalTest/resources/documentgenerator/da.json
  src/functionalTest/resources/documentgenerator/documents/jsoninput/DA-granted-letter.json
  src/functionalTest/resources/documentgenerator/documents/pdfoutput/DA-granted-letter.pdf
  src/functionalTest/resources/documentgenerator/documents/regenerated/.gitignore
  src/functionalTest/resources/documentgenerator/invalid-template-data.json
  src/functionalTest/resources/documentgenerator/invalid-template-name.json
  src/functionalTest/resources/documentgenerator/valid-input.json
  src/integrationTest/java/uk/gov/hmcts/reform/prl/DocumentGeneratorControllerIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/prl/DocumentGeneratorUtil.java
  src/integrationTest/java/uk/gov/hmcts/reform/prl/DocumentManagementServiceImplIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/prl/IdamUtils.java
  src/integrationTest/java/uk/gov/hmcts/reform/prl/IntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/prl/ServiceContextConfiguration.java
  src/integrationTest/resources/application-aat.properties
  src/integrationTest/resources/application-saat.properties
  src/integrationTest/resources/application.properties
  src/integrationTest/resources/documentgenerator/requests/C100-case-data.json
  src/integrationTest/resources/documentgenerator/requests/FL401-case-data.json
  src/integrationTest/resources/documentgenerator/requests/invalid-template-data.json
  src/integrationTest/resources/example-application-local.properties
  src/integrationTest/resources/tempOutput.pdf
  src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/controller/DocumentGenerateDownloadController.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/controller/DocumentGenerateDownloadControllerTest.java
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-90

#91 Update application.yml
  config/owasp/suppressions.xml
  dependency-check-suppressions.xml
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-91

#93 Merge to master
  charts/prl-dgs/Chart.yaml
  charts/prl-dgs/values.aat.template.yaml
  charts/prl-dgs/values.preview.template.yaml
  charts/prl-dgs/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-93

#96 Prl springboot version revert
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/DocumentGenerateControllerFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/ResourceLoader.java
  src/functionalTest/java/uk/gov/hmcts/reform/prl/functionaltest/RootControllerFunctionalTest.java
  src/functionalTest/resources/documentgenerator/da.json
  src/functionalTest/resources/documentgenerator/documents/jsoninput/DA-granted-letter.json
  src/functionalTest/resources/documentgenerator/documents/pdfoutput/DA-granted-letter.pdf
  src/functionalTest/resources/documentgenerator/documents/regenerated/.gitignore
  src/functionalTest/resources/documentgenerator/invalid-template-data.json
  src/functionalTest/resources/documentgenerator/invalid-template-name.json
  src/functionalTest/resources/documentgenerator/valid-input.json
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-96

#98 Dependency suppressed for Spring framework
  dependency-check-suppressions.xml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-98

#101 added suppression for nightly test pipeline
  Jenkinsfile_nightly
  config/owasp/suppressions.xml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-101

#109 suppressed CVE
  config/owasp/suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-109
