Repository hmcts/prl-dgs-api, pull requests merged in 2023-04, with the labels that each got.

#232 Upgrade Dockerfile
  Dockerfile
  config/owasp/suppressions.xml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-232

#234 downgrade pact plugin for fixing build issue
  build.gradle
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-234

#203 C7 template and filename is updated for draft
  src/contractTest/resources/application.yml
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-203, keep-helm

#238 Added SDO to dgs
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-dgs-pr-238
