Repository hmcts/prl-dgs-api, pull requests merged in 2023-07, with the labels that each got.

#269 Adding access code cover letters
  config/owasp/suppressions.xml
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-269

#271 Update application.yml
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, rel:prl-dgs-pr-271

#272 java 17 and gradel 7 upgrade
  Dockerfile
  build.gradle
  charts/prl-dgs/Chart.yaml
  charts/prl-dgs/values.preview.template.yaml
  charts/prl-dgs/values.yaml
  checkstyle.xml
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/prl/documentgenerator/controller/DocumentGeneratorController.java
  src/test/java/uk/gov/hmcts/reform/prl/documentgenerator/management/monitoring/health/HealthCheckITest.java
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-dgs-pr-272

#270 SNI-4206 fixed welsh seal for english documents
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-dgs-pr-270
