Repository hmcts/prl-dgs-api, pull requests merged in 2024-03, with the labels that each got.

#297 PRL-5323: added template for welsh C7
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-dgs-pr-297

#292 PRL-4449-DA-List-on-Notice
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-dgs-pr-292

#294 PRL-5203-CA-Personal-Service-Unrepresented-Applicant-Post
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-dgs-pr-294

#295 prl_2692_Respondent_Solicitor_C7_Docmosis_Welsh: added Welsh C7 file properties
  charts/prl-dgs/values.preview.template.yaml
  src/contractTest/resources/application.yml
  src/main/resources/application.yml
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-dgs-pr-295
